// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEor-PquRS2YOWSt3fwkll3uKYvjwx2sA',
    appId: '1:521561907673:web:0f97a691cdf229420879c8',
    messagingSenderId: '521561907673',
    projectId: 'cash-out-f5c4c',
    authDomain: 'cash-out-f5c4c.firebaseapp.com',
    storageBucket: 'cash-out-f5c4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHaFbDF4-ciYtgS7HOdSYQjfBvGAMO80M',
    appId: '1:521561907673:android:e9cf387eae947f240879c8',
    messagingSenderId: '521561907673',
    projectId: 'cash-out-f5c4c',
    storageBucket: 'cash-out-f5c4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAoAvPAxHW8jXS87aUZByiV57-5k5YvhA',
    appId: '1:521561907673:ios:12485202a278239a0879c8',
    messagingSenderId: '521561907673',
    projectId: 'cash-out-f5c4c',
    storageBucket: 'cash-out-f5c4c.firebasestorage.app',
    iosBundleId: 'com.example.cashOut',
  );
}
